### ISSUE TITLE
Incompatibility with UNO (and even Nano). Any ideas?

### ISSUE THREAD

**Issue by KA1GT** [kk4das/IC746CAT#6]
Has anyone ever compiles this for an Arduino UNO?  It crashes every time for me with a "Error compiling for board Arduino Uno" message, even on the included example program. Even a a program that does nothing other than include the library. The introduction here says..."It has been demonstrated to work with an Arduino Nano and Arduino Nano Every although it should work with any MCU with a serial port..."

I tried it with an Arduino Nano and I get  "Error compiling for board Arduino Nano", so that's not helping either.

I'm using Arduino IDE v1.8.15 if that makes a difference.

Same system, same cables, same port, same boars and same MPU with any other Arduino sketch sketch has no problems on UNO or Nano.  I've tried all the usual things, restarting IDE, unpluging and reconnecting USB, different USB port etc, but still no joy when using this library.  Any idea what's going on?

**Comment by kk4das** [comment]
Hi –

 

It compiles fine for both Nano and Uno on 1.8.19 but I don’t think the version should matter.

 

I’ll help if I can.  What platform are you compiling on?  How did you install the library?  What are you using for the main sketch?

 

Thanks,

 

Dean

 

 

From: bob04609 ***@***.***> 
Sent: Saturday, January 7, 2023 10:46 PM
To: kk4das/IC746CAT ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kk4das/IC746CAT] Incompatibility with UNO (and even Nano). Any ideas? (Issue #6)

 

Has anyone ever compiles this for an Arduino UNO? It crashes every time for me with a "Error compiling for board Arduino Uno" message, even on the included example program. Even a a program that does nothing other than include the library. The introduction here says..."It has been demonstrated to work with an Arduino Nano and Arduino Nano Every although it should work with any MCU with a serial port..."

I tried it with an Arduino Nano and I get "Error compiling for board Arduino Nano", so that's not helping either.

I'm using Arduino IDE v1.8.15 if that makes a difference.

Same system, same cables, same port, same boars and same MPU with any other Arduino sketch sketch has no problems on UNO or Nano. I've tried all the usual things, restarting IDE, unpluging and reconnecting USB, different USB port etc, but still no joy when using this library. Any idea what's going on?

**Comment by KA1GT** [comment]
Hi Dean

Many thanks for the reply. I may be missing some critical step in the setup which is obvious to you, but not to me!

My system is Windows 7 pro.  I installed the library in the usual way. Down load the zip file from Github, then use the Arduino IDE (1.8.15) to install the zip file.  I've done this many times with many libraries with no problems.

Then I navigate to the example file in the library, open it in the IDE, check that it compiles then try to upload it to an Arduino (first checking that I have the correct Arduino model and correct serial port selected). At this point the compiler and loader do their things and the compiled code gets loaded into the Arduino and runs.

Although I don't actually have the Adafruit ILI9341 tft, the compiler doesn't know that, so it should compile and even load (but of course it would not run). If I can get to the point of a successful compile and upload, then I'll change the TFT code to code that drives an OLED display.

However. with the example sketch (or indeed when I make any reference to the IC746 library even in an otherwise empty sketch)  I get complaints from the compiler about aspects of the code and the IDE complains about compiling for the Arduino UNO (or Nano).  The complaint about the UNO/Nano may be spillover from the earlier compiler compilates about the code and not in fact be complains about the board. Errors can cascade of course.

BTW I have gotten the C07WT Yaesu FT-857D library to work OK on an Arduino and I think your library is somewhat based on that.  However the  857D is limited to 10Hz steps and in fact that library truncates frequencies to the nearest 100Hz. I'd like 1Hz steps and the actual IC746 does support 1Hz steps via CAT (not sure if your library does).

I've attached the verbose compiler output messages (most of which I don't understand) in case that gives you any clues. I'm not much of a C++ programmer.

My assumption was that I should be able to load the library, load the example sketch in the IDE and it should compile without me needing to do anything else, just like pretty much any other library and example sketch.  Am I missing something here?

I may try installing the latest IDE on another PC running WIndows 10 (the most recent v2 IDE only lists full compatibility with Windows 10 and up) and see if that makes any difference. However, the fact that it works for you on the Arduino with the v1 IDE suggests that it should work for me too.

If I'm making some stupid error, please feel free to point it out. It wouldn't be the first time!

Thanks and 73
Bob, KA1GT

________________________________

**Comment by KA1GT** [comment]
Hi Dean

An update here.  I installed the Arduino IDE v 2.0.3 on a Windows 10 machine, and with that setup your library code compiles OK.  I have not yet figured out what is happening with v1.8.15 on the Windows 7 machine. Obviously, something is wrong and it seems to be a compiler error of some sort, possibly in some intrinsic functions . Maybe something is out of date or there is a conflict somewhere.

I did find a small issue with the compiled code on the Windows 10 machine however. It seems to be fine up to 99Mhz, but at 100MHz and up it seems to be dropping the leading digit (100's of MHz). This gives errors when trying to use it at 144MHz.  On my IC-7100, I think it's a 5 byte BCD coding for the frequency and the 5th byte has the high 4 bits as GHz (so it's always zero) and the now 4 bytes as the 100Mhz multiplier, so for the 746 it has to be 1 or 0 since the VHF/UHF frequency coverage is limited to the 2m band (on the IC-7100 it can be 0-4).

I have not yet tried looking at the .cpp file in your library, but I suspect there's an issue with the BCC to decimal and/or the decimal to BCD conversion routines which may only be looking at the lower 4 bytes of the frequency information.  If I get a chance, I'll take a look at that tomorrow. I also have to get things running with the OLED display. I'm currently using WSJTX to check on how it's working (all seems OK there except for the frequency error above 99.999999 MHz). That's probably using the latest HamLib library. Omnirig also seems to find an IC746 just fine, though I have not tried using it to sending any commands.

73
Bob, KA1GT.
________________________________

**Comment by kk4das** [comment]
Bob,

 

Glad to hear it is working under Win 10.  I no longer have a Win 7 environment.  I’m sure you are right about the BCD conversion code.  It’s a dumb byte by byte routine and I am certain I never thought about frequencies at 100MHz and up.  Should be a pretty easy fix – you’ll need to look at both directions.

 

Another ham has made some changes to additional modes – CWU and CWL – those aren’t working quite right yet – but when they are I’ll push out a new version.  Let me know if your test works ok and I’ll merge your changes as well.,

 

Glad to hear WSJTX is working.  I’ve been away from this code for a while – there was an issue with CIV routines that I worked with them on about a year and half ago.  I think I am still using a temporary hamlib I built to work around the issue.

 

73,

Dean

KK4DAS

**Comment by KA1GT** [comment]
Hi Dean

Well so far I seem to be missing something.  I think the BCD/decimal changer I made are correct. For BCD to decimal I think you simply ignore what's in the 5th byte of the cmdBuf array, so I added in what I think is the correct code the read them and add then to the frequency (freq(.

long IC746::BCDtoFreq() {
  long freq;

  freq = cmdBuf[CAT_IX_FREQ] & 0xf;                 // lower 4 bits
  freq += 10L * (cmdBuf[CAT_IX_FREQ] >> 4);          // upper 4 bits
  freq += 100L * (cmdBuf[CAT_IX_FREQ + 1] & 0xf);
  freq += 1000L * (cmdBuf[CAT_IX_FREQ + 1] >> 4);
  freq += 10000L * (cmdBuf[CAT_IX_FREQ + 2] & 0xf);
  freq += 100000L * (cmdBuf[CAT_IX_FREQ + 2] >> 4);
  freq += 1000000L * (cmdBuf[CAT_IX_FREQ + 3] & 0xf);
  freq += 10000000L * (cmdBuf[CAT_IX_FREQ + 3] >> 4);
  // add in 100Mhz and 1000Mhz byte
  freq += 100000000L * (cmdBuf[CAT_IX_FREQ + 4] & 0xf);
  freq += 1000000000L * (cmdBuf[CAT_IX_FREQ + 4] >> 4);


  return freq;
}

When you write the frequency you simply put 0 in the 5th byte of the buffer. I defined two new variables, hund_mil and thou_mil to handle the 100MHz and 1000MHz data.

  byte ones, tens, hund, thou, ten_thou, hund_thou, mil, ten_mil, hund_mil, thou_mil;

  ones =     byte(freq % 10);
  tens =     byte((freq / 10L) % 10);
  cmdBuf[CAT_IX_FREQ] = byte((tens << 4)) | ones;

  hund =      byte((freq / 100L) % 10);
  thou =      byte((freq / 1000L) % 10);
  cmdBuf[CAT_IX_FREQ + 1] = byte((thou << 4)) | hund;

  ten_thou =  byte((freq / 10000L) % 10);
  hund_thou = byte((freq / 100000L) % 10);
  cmdBuf[CAT_IX_FREQ + 2] = byte((hund_thou << 4)) | ten_thou;

  mil =       byte((freq / 1000000L) % 10);
  ten_mil =   byte(freq / 10000000L);
  cmdBuf[CAT_IX_FREQ + 3] = byte((ten_mil << 4)) | mil;

  //cmdBuf[CAT_IX_FREQ + 4] = 0; // fixed //ORIGINAL

  //add in 100MHz and 1000Mhz values
  hund_mil =   byte((freq / 100000000L) % 10);
  thou_mil =   byte(freq / 1000000000L);
  cmdBuf[CAT_IX_FREQ + 4] = byte((thou_mil << 4)) | hund_mil;

}

I was hoping that this would be all that was required, but unfortunately it didn't fix the problem. When using WSJTX and entering a frequency below 100 MHZ (e.g. 70, 50 or 28MHz), everything is file and Doppler tracking for EME works as it should. However, when any frequency over 100MHz (e.g. 144MHz) is used, the frequency changes in an unpredictable way, 144 may go to 288 then 325 etc. I assume it's writing the wrong frequency above 100MHz. I don't yet have a display capable of printing out the debug commands in any legible manner.

I know it's very hard to remember what you did in code you wrote years ago, but do you remember if there is anywhere else you are just using 4 bytes of data in place of the 5 bytes that are allocated for frequency in the CI-V commands for the IC746? Right now I don't see it.

Enabling the debug commands probably means I will have to modify the .ino file to output the data to a second serial port and I don't have the hardware for that on hand (serial->USB) and maybe I will need to run it on a Mega board (which has additional serial lines), assuming it will compile for it.  If you still have your original hardware around, maybe you could take a look and see if the Debug functions give any clues to what's happening here.  Is it writing the wrong frequency of reading the wrong frequency (or both?)?

I will persist, but I'm currently a bit lost in the library code. You do seem to be allocating 5 bytes for the frequency along with the addresses for the frequency read command.

#define CAT_SZ_FREQ        8   //  8 bytes - E0 56 03 ff ff ff ff ff  (frequency in little endian BCD)

I have not yet figured out how (or where) you are setting the frequency.

So right now I'm stuck unless you have any ideas!

73
Bob, KA1GT
________________________________

**Comment by kk4das** [comment]
I’ll try to look at it in the next day or two.  The basic fix looks right.  I’d check the size of CmdBuf to make sure we are not overwriting memory.  And then there is the length of the command we send to the radio.  A second serial port is definitely helpful.  Or some kind of display for debug messages.

 

 

73,

Dean

**Comment by KA1GT** [comment]
Hi Dean

Thanks.  I checked operation with Flrig and it shows similar problems to WSJTX when the frequency goes over 99.999999MHz.  I do have the debug operating on a tiny OLED now, just showing frequency sent and frequency received. It seems to be sending the right frequency (expressed as an integer) but somehow it's not getting back rig correctly.

It's tough to explain what I see happening, but I'll give it a try.
Using the arduino and FLrig I the 3 readouts.  There's an Arduino debug readout of the GetFreq and SetFreq and there's the FLrig display of where it thinks the rig is tuned

GetFreq         SetFreq         Flrig
99.999999    99.999999    99.999999    - all is good
increade frequency by 1Hz in FLrig
100.000000  100.000000  200.000000
Increase frequency by 1Hz in Flrig
200.000001  200.000001  240.000001
Increase Frequency by 1Hz n FLrig
240.000002  240.000002  280.000002

So when adding 1Hz (in FLrig), it's adding 1Hz to the FLrig frequency and sending a request to move to that frequency. So it thinks it's at 200MHz, when 100MHz should have been sent, then when it adds 1Hz it now asks for 200.000001 MHz to be set on the rig (i.e. the emulator).

I don't know why it adds an extra 100MHZ the first time, then 40MHz after that. If you keep adding 1Hz, it stars to jump around, from 240 MHz to 280 MHz to 320MHz, then back to 300MHz then up to 440Mhz, 520, 540, 560, 580 etc. It's clearly not getting the right BCD in the 5th frequency byte.

It seems as though the emulator has the correct frequency in it, but when it gets over 100MHz, the decimal number it sends back is either not converted correctly BCD (though the code for that looks good), or the BCD is not sent back to the control program in the correct format data stream. Something is happening to that 5th BCD byte.

That's about the limit of my analysis. I start to go out of my depth beyond this point. I hope you can make some sense of it!

Thanks again and 73
Bob, KA1GT
________________________________

**Comment by KA1GT** [comment]
Hi Dean. Not much luck sorting things out with the IC746 library and CAT control over 100MHz.  I wonder if you had any time to look at it? I think my modifications to your library to add BCD/Decimal conversions which include the 5th Byte (100MHz and 1000MHz) are OK, and I think they work to pass frequencies back and forth to the Arduino emulator using OmniRig (OmniRig Client.exe program) on the PC end. I seem to be able to set VFOA and VFOB by toggling A and B and uploading a frequency to the active VFO. Seems to work OK at 144MHz.

However, things don't work with WSJTX (presumably using HamLib). I tried WSJTX with OmniRig (there's a Rig setting for OmniRig in the rig menu), but it didn't work. I'm not surprised since I suspect that the OmniRig interface is not used by anyone and may not work for anything! I'll have to see if it works with a real radio attached.

Though I've worked with OmniRig in the past (don't really understand it all, but I can get by using it), but I've never even looked at what goes in inside the HamLib "black box".

If you have had a chance to look at it, or have any thoughts what might be going on with Hamlib, I'd be interested to hear from you.

73
Bob, KA1GT
________________________________

**Comment by kk4das** [comment]
HI Bob – 

 

I looked at it this morning and the changes look right to me.  I don’t’ see anything obvious.  If it works with OmniRig that is a good sign.  You might try some other software like FLDIGI  and FLRIG.    If I recall FLRIG has a trace mode that lets you see the packets.   I also used program called CatBkt <https://www.maniaradio.it/en/catbkt.html>  for testing.  If it works with all of these then it points to a Hamlib issue.  I didn’t find the hamlib team particularly responsive when I had other issues with WSJTX – it took the WSJTX developers weighing in to get them to fix the code.  They were sending unimplemented commands to the IC-746 that were messing things up.   You could try posting a question / bug report on the WSJTX groups.io and see.  The lead developer passed away last year, and I don’t know who has stepped in.

 

73,

Dean

KK4DAS

**Comment by KA1GT** [comment]
Thanks Dean

I will try a few more programs with the emulator, maybe even try to do some more testing with OmniRig.  I would not be surprised at HamLib issues. They happen all the time with WSJTX. I knew Bill  Somerville quite well, and he was certainly the "go to" guy for any deep technical, PC related questions about WSJTX. It has been very difficult fining anyone else who knows what's going on as thoroughly as Bill did. I think HamLib questions are now being bounced back to the HamLib team for resolution, which has significantly slowed things down. If they don't get complaints from IC746 users, I suspect it's unlikely they want to spend time looking at emulator issues.  Things seem to work OK as long as you are under 100MHz, so I don't quite know what that's pointing to. I might try contacting them if all else fails. At least they might understand the Hamlib failure message that appears when WSJTX fails the CAT test!

I'll take a look at CatBkt and a second look at OmniRig. If I can't figure out what's going on, I'll try a few questions in relevant groups to see if anyone else has run into this issue.

I'll certainly let you know what I find out.

73
Bob, KA1GT
________________________________

**Comment by kk4das** [comment]
Bill was a great guy.  If you search the WSJX groups.io you'll see he the
one that got the Hamlib guys to make the last fix I needed.

Dean

**Comment by KA1GT** [comment]
Hi Dean

I found the problem! After putting a serial line monitor on the connection between the application and the emmulator and analyzing the CI-V trafic, it was clear that the problem was in the decimal to BCD conversion. It was missing a mod 10 (% 10) in the final conversion line of your original code. This is absolutely fine for frequences <100 Mhz, but not for frequencies >=100MHz. Even for frequences <100Mhz, the mod 10 does no harm, it's just not needed. At and above 100Mhz it is needed, a fact that I had missed when adding the BCD Code for the hundreds of MHz digit as shown below:

void IC746::FreqtoBCD(long freq) {
//  byte ones, tens, hund, thou, ten_thou, hund_thou, mil, ten_mil;

byte ones, tens, hund, thou, ten_thou, hund_thou, mil, ten_mil, hund_mil, thou_mil;

  ones =     byte(freq % 10);
  tens =     byte((freq / 10L) % 10);
  cmdBuf[CAT_IX_FREQ] = byte((tens << 4)) | ones;

  hund =      byte((freq / 100L) % 10);
  thou =      byte((freq / 1000L) % 10);
  cmdBuf[CAT_IX_FREQ + 1] = byte((thou << 4)) | hund;

  ten_thou =  byte((freq / 10000L) % 10);
  hund_thou = byte((freq / 100000L) % 10);
  cmdBuf[CAT_IX_FREQ + 2] = byte((hund_thou << 4)) | ten_thou;

  mil =       byte((freq / 1000000L) % 10);
  //ten_mil =   byte(freq / 10000000L);   <- This is your original line, which is fine only if the result of this integer division is <10
  ten_mil =   byte(freq / 10000000L) % 10; <- This is the revised line which is good whether the resuly is <10 or >10
  cmdBuf[CAT_IX_FREQ + 3] = byte((ten_mil << 4)) | mil;

  //cmdBuf[CAT_IX_FREQ + 4] = 0; // fixed //ORIGINAL

  //add in 100MHz and 1000Mhz values
  hund_mil =   byte((freq / 100000000L) % 10);
  thou_mil =   byte(freq / 1000000000L); <- Note that like the above, this is only good when the result is <10 (which is always the case for the IC-746)
//thou_mil =   byte(freq / 1000000000L % 10); <- This would be the more general case and allow frequencies up to 9999.999999 MHz to be enterd
                                                                                        The code could then be used for the IC-9100 for example

  cmdBuf[CAT_IX_FREQ + 4] = byte((thou_mil << 4)) | hund_mil;

}

Since the library does not use the default received address code (56 for the IC-746), and only basic CI-V codes are supported, the library will almosr certainly emulate the IC-9100 (which has 23cm coverage) with the line shown in blue used.

As far as I can tell, it's now working fine at 144MHz (and indeed 432MHz, which the IC-746 doesn't cover!). If it passes any tests you make, feel free to use it to modify the Arduino library if you wish to.

I think this solves all the problems. I've learrned a little about CI-V, arduino librariers and BCD coversion in the process of figuring it out, so it's been a valuable learning experience.

Thanks and 73
Bob, KA1GT

**Comment by kk4das** [comment]
Bob,

That's a good catch and a very satisfying fix.  I will definitely include
it in the next update. I'm integrating another hams changes to add CWU and
CWL modes. I'll put those together and make a new release.  I suspect you
are correct that the existing code will work with other  ICOMs.  I tried to
make the responses to unsupported commands at least reasonable. But I can't
say for sure that the existing code will work for any command that might
get sent from a model with an advanced CI-V.   Split mode in WSJTX is one
of the ones that can trip you up. As long as you use split mode emulated in
WSJTX. It should work for any of them.

What did you use serial port monitoring? I mostly used the command line
version of the Hamlib utility, but that had its limitations.

Our club has an IC-746 and I'm going to borrow it to characterize all of
the command and response streams.

73,
Dean

**Comment by kk4das** [comment]
Bob,

The library has been updated with your changes to the BCD routines.  I have also added support for all IC-746 defined operating modes. 

Thanks for everything.

73,
Dean
KK4DAS

**Comment by kk4das** [comment]
Issue resolved in release 1.0.3
